import type { Project, LogItem } from '../types';

export const MOCK_PROJECTS: Project[] = [
    {
        id: 'p1',
        name: 'Sample Guest',
        client: 'BESVECA',
        email: 'guest@example.com',
        phone: '(555) 010-2026',
        hourlyRate: 0,
        status: 'ACTIVE',
        createdAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
    },
    {
        id: 'p2',
        name: 'Owner Maintenance',
        client: 'BESVECA',
        hourlyRate: 0,
        status: 'ACTIVE',
        createdAt: Date.now() - 1000 * 60 * 60 * 24 * 15,
    },
    {
        id: 'p3',
        name: 'Skyhouse Sample Guest',
        client: 'Skyhouse',
        email: 'skyhouse.guest@example.com',
        hourlyRate: 0,
        status: 'ACTIVE',
        createdAt: Date.now() - 1000 * 60 * 60 * 24 * 60,
    },
];

export const MOCK_LOGS: LogItem[] = [
    {
        id: 'l1',
        projectId: 'p1',
        date: new Date().toISOString().split('T')[0],
        description: 'Four-night guest stay',
        type: 'STAY',
        client: 'Sample Guest',
        checkIn: '2026-06-05',
        checkOut: '2026-06-09',
        cost: 525,
        cleaningCount: 1,
        cleaningFee: 275,
        poolHeat: 150,
        tax: 315.63,
        billableAmount: 2840.63,
        createdAt: Date.now() - 1000 * 60 * 60 * 2,
    },
    {
        id: 'l2',
        projectId: 'p2',
        date: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString().split('T')[0],
        description: 'Replacement linens',
        type: 'EXPENSE',
        cost: 184.32,
        markupPercent: 0,
        billableAmount: 184.32,
        profit: 0,
        createdAt: Date.now() - 1000 * 60 * 60 * 25,
    },
    {
        id: 'l3',
        projectId: 'p3',
        date: new Date().toISOString().split('T')[0],
        description: 'Weekend guest stay',
        type: 'STAY',
        client: 'Skyhouse Sample Guest',
        checkIn: '2026-06-12',
        checkOut: '2026-06-14',
        cost: 425,
        cleaningCount: 1,
        cleaningFee: 225,
        poolHeat: 0,
        tax: 134.38,
        billableAmount: 1209.38,
        createdAt: Date.now() - 1000 * 60 * 60 * 5,
    },
];
